# Generated by Django 4.0.10 on 2023-12-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeProm', models.CharField(max_length=30, verbose_name='Code-Semestre')),
                ('LibProm', models.CharField(max_length=50, verbose_name='Libéllé-Semestre')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeSec', models.CharField(max_length=30, verbose_name='Code-Semestre')),
                ('LibSec', models.CharField(max_length=50, verbose_name='Libéllé-Semestre')),
            ],
        ),
    ]
