# Generated by Django 4.0.10 on 2023-10-31 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_eleve_classe_eleve_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passer',
            name='max_cours',
        ),
    ]
