# Generated by Django 4.0.10 on 2023-10-31 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_passer_eleve_pas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passer',
            name='cours_pas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cours', verbose_name='Cours'),
        ),
        migrations.AlterField(
            model_name='passer',
            name='epreuve_pas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.epreuve', verbose_name='Epreuve'),
        ),
    ]
