# Generated by Django 4.0.10 on 2023-10-31 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_passer_cours_pas_alter_passer_epreuve_pas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passer',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.periode', verbose_name='Période'),
        ),
    ]
