# Generated by Django 4.0.10 on 2023-11-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_epreuve_max_epr_alter_cours_ponderation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epreuve',
            name='Lib_epr',
            field=models.CharField(max_length=10, verbose_name='Libéllé-Epreuve'),
        ),
    ]
