# Generated by Django 4.0.10 on 2023-11-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_epreuve_lib_epr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epreuve',
            name='code_epr',
            field=models.CharField(max_length=4, verbose_name='Code-Epreuve'),
        ),
    ]
