# Generated by Django 4.0.10 on 2023-11-27 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_epreuve_code_epr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semestre',
            old_name='code_per',
            new_name='code_sem',
        ),
        migrations.RenameField(
            model_name='semestre',
            old_name='lib_semestre',
            new_name='lib_sem',
        ),
    ]
