# Generated by Django 4.0.10 on 2023-11-27 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_code_per_semestre_code_sem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='code_cour',
            new_name='code_cours',
        ),
    ]
