# Generated by Django 4.0.10 on 2023-11-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_code_cour_cours_code_cours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
    ]
