# Generated by Django 4.0.10 on 2023-09-26 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=225, verbose_name='Nom')),
                ('last_name', models.CharField(default='', max_length=225, verbose_name='Post_nom')),
                ('city', models.CharField(default='K', max_length=225, verbose_name='ville')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Phone')),
                ('image_parent', models.ImageField(blank=True, default='', upload_to='post_image/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
